### ISSUE TITLE
Cannot remove unused Android devices from device list

### ISSUE THREAD

**Issue by adrianghc** [MahdiGhiasi/Roamit#14]
The last update added the ability to remove unused Android devices from the device list, which is a very good idea (thank you!) - only that the link to do this is greyed out, and clicking it will highlight the "Default file receive location" text box. I can provide more information as needed.

**Comment by MahdiGhiasi** [comment]
On the Account section of settings, please tap Sign In link and sign in to Roamit Cloud Service. Then the "Remove unused Android devices" setting will be enabled and you can remove them.

**Comment by adrianghc** [comment]
I see. The UI does not make this clear, though, I think that could be improved. Also, why does this require signing in to the Roamit Cloud Service?

**Comment by MahdiGhiasi** [comment]
Thanks for the suggestion. I'll improve the UI.

As for the Roamit Cloud Service, there are essentially two methods that Roamit uses for authenticating users. Communication to Android devices still uses the legacy system, but since removing unused phones is a new feature, it uses the new system. The old system will be deprecated in the future as things migrate to the new one.
